version: "3.7"

services:
  app:
    build: ./
    ports:
      - 80:3000
    volumes:
      - ./:/app/server
    environment:
      - TZ=Asia/BeiJing
  # redis:
  #   image: redis:5.0.13
  #   volumes:
  #     - redis:/data
  #   environment:
  #     - TZ=Asia/BeiJing
# volumes:
#   redis:
